# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pipeci < Formula
  desc "CLI Program for CI/CD Pipeline execution."
  homepage ""
  version "0.0.3"
  license "Unlicense"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/CS6510-SEA-SP25/t3-cicd/releases/download/v0.0.3/pipeci_Darwin_x86_64.tar.gz"
      sha256 "adbe1d11f3c33046516f5b79afd482cd7aa9911c0fb88320bacca30bc0bfd007"

      def install
        bin.install pipeci
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/CS6510-SEA-SP25/t3-cicd/releases/download/v0.0.3/pipeci_Darwin_arm64.tar.gz"
      sha256 "6fb4ccd1b20bfd306f9a504b74b1fe5fb99613fc60a3c3d083289d3c3d65cdf4"

      def install
        bin.install pipeci
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/CS6510-SEA-SP25/t3-cicd/releases/download/v0.0.3/pipeci_Linux_x86_64.tar.gz"
        sha256 "8def529a3717e279edc5b4f0b9d5375dd394b36ad931f9723b688b458ac5b9d2"

        def install
          bin.install pipeci
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/CS6510-SEA-SP25/t3-cicd/releases/download/v0.0.3/pipeci_Linux_arm64.tar.gz"
        sha256 "76575084aa418a0401708027c76a3ce1abd52556a6e59ca6c7cb11d9795ecb00"

        def install
          bin.install pipeci
        end
      end
    end
  end

  test do
    system "#{bin}/pipeci --version"
  end
end
