# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pipeci < Formula
  desc "CLI Program for CI/CD Pipeline execution."
  homepage ""
  version "0.0.2"
  license "Unlicense"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/CS6510-SEA-SP25/t3-cicd/releases/download/v0.0.2/pipeci_Darwin_x86_64.tar.gz"
      sha256 "0a5b6234bed2ce1a41abe9377b4701def9851ea2ac7de778dfb1c3a4cfa4917f"

      def install
        bin.install pipeci
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/CS6510-SEA-SP25/t3-cicd/releases/download/v0.0.2/pipeci_Darwin_arm64.tar.gz"
      sha256 "6ab696054827d10dc8dad1d40e78d0f450f5692c562056fe1374568e2aabf268"

      def install
        bin.install pipeci
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/CS6510-SEA-SP25/t3-cicd/releases/download/v0.0.2/pipeci_Linux_x86_64.tar.gz"
        sha256 "6dc5ca455921e7b2c8bc6a732352e200d666d09d9a0a3675c6b604252df70bae"

        def install
          bin.install pipeci
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/CS6510-SEA-SP25/t3-cicd/releases/download/v0.0.2/pipeci_Linux_arm64.tar.gz"
        sha256 "23fc143d7c80293d286345c86a59e7d4199ae5ff8d6e139cdbc59a75f568f2e7"

        def install
          bin.install pipeci
        end
      end
    end
  end

  test do
    system "#{bin}/pipeci --version"
  end
end
